name: Test calculator
on: [push]

jobs:

  documentation: 
    name: Build documentation
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository content
        uses: actions/checkout@v2
        with: 
          path: ./main


      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Build documentation
        run: |
          javadoc ./src/main/java/dhbw/Calculator1.java
        working-directory: ./main/src/calculator/


  calculator:
    name: Build and run frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2
        with: 
          path: ./main

      - name: Checkout gh-pages content
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ./gh-pages

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: |
          chmod +x ./gradlew
          ./gradlew test
        working-directory: ./main/src/calculator/

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: ./main/src/calculator/build/reports/tests/test/

      - name: Copy report to gh-pages
        if: always()
        run: |
          rm -rdf ./gh-pages/docu/*
          cp -r ./main/src/calculator/build/reports/tests/test/* ./gh-pages/docu

      - name: Upload to repo
        if: always()
        run: |
          git config --global user.name 'Test result pusher'
          git add -A
          git commit -m 'Add test results for ${{ github.sha }}'
          git push
        working-directory: ./gh-pages
