name: Build and Test
on: [push]

jobs:

  calculator:
    name: Build and run frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: |
          chmod +x ./gradlew
          ./gradlew test
        working-directory: ./src/calculator/

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: ./src/calculator/build/reports/tests/test/index.html
